#!/usr/bin/env python3
"""Emit one SQL file that takes an empty MySQL server to a working F2H database.

    cd backend
    python database/build_full_schema.py            # writes database/f2h_complete.sql
    python database/build_full_schema.py --stdout   # or print it

Then, on the target server:

    mysql -u root -p < database/f2h_complete.sql

Why this is a generator rather than a checked-in .sql file
----------------------------------------------------------
The 40 base tables have no SQL source. They are declared in `app/models/*.py`
and created by SQLAlchemy's `create_all()` on first run, so the models are the
only description of them that exists. A hand-written schema file would be a
*second* description, and the two would drift the first time a column changed —
silently, because nothing checks one against the other.

This reads the models and emits exactly what SQLAlchemy would create, for the
MySQL dialect specifically, so `VARCHAR(120)`, `DECIMAL(10,2)` and every foreign
key come out as MySQL spells them rather than in the abstract.

What it produces, in order
--------------------------
    1. CREATE DATABASE + USE
    2. The 40 base tables, in dependency order so no FK points at a table that
       does not exist yet
    3. The 14 migrations from f2h_full_migration.sql, unchanged
    4. The three roles, which the app needs before anyone can register

Not included: the admin account. `seed_admin.py` hashes the password with bcrypt
and reads it from the environment, and putting a password in a SQL file — where
it lands in shell history, backups and any repository this is committed to — is
how the credentials that started this project got exposed. Run `python
seed_admin.py` after this instead.
"""
import argparse
import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
BACKEND = HERE.parent
sys.path.insert(0, str(BACKEND))


def build(db_name: str) -> str:
    from sqlalchemy.schema import CreateTable
    from sqlalchemy.dialects import mysql

    from app import create_app          # noqa: E402
    from app.extensions import db       # noqa: E402
    import app.models                   # noqa: F401,E402  (registers every model)

    app = create_app()
    out = []

    def rule(title):
        out.append("-- " + "=" * 74)
        out.append("-- " + title)
        out.append("-- " + "=" * 74 + "\n")

    out.append(f"""-- F2H Market — complete database, from nothing to running.
--
--     mysql -u root -p < database/f2h_complete.sql
--     python seed_admin.py          # afterwards, for the admin account
--
-- Generated by database/build_full_schema.py from the SQLAlchemy models, so
-- this is what the application actually expects rather than a transcription of
-- it. Regenerate after any model change; do not hand-edit.
--
-- Sections 1-2 are for an empty server. Sections 3-4 are safe to re-run on a
-- database that already exists, so this same file also brings an older
-- deployment up to date.

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;
""")

    rule("SECTION 1 of 4  .  The database itself")
    out.append(f"CREATE DATABASE IF NOT EXISTS `{db_name}`")
    out.append("  CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;")
    out.append(f"USE `{db_name}`;\n")

    with app.app_context():
        tables = db.metadata.sorted_tables      # dependency order, FKs resolve
        rule(f"SECTION 2 of 4  .  Base tables ({len(tables)}), in dependency order")
        out.append("-- Straight from the models. `sorted_tables` orders them so that no\n"
                   "-- foreign key references a table that has not been created yet.\n")
        for table in tables:
            ddl = str(CreateTable(table).compile(dialect=mysql.dialect())).strip()
            # CreateTable omits the storage clause; the app assumes InnoDB for
            # its foreign keys and utf8mb4 for Indian-language product names.
            out.append(ddl.rstrip(";\n ") +
                       "\n  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;\n")

    rule("SECTION 3 of 4  .  Migrations")
    combined = HERE / "f2h_full_migration.sql"
    if combined.exists():
        out.append("-- Verbatim from f2h_full_migration.sql. Every statement there is\n"
                   "-- guarded, so on the fresh tables above they simply report that the\n"
                   "-- column already exists — the models already include these changes.\n"
                   "-- They matter when this file is run against an older database.\n")
        out.append(combined.read_text())
    else:
        out.append(f"-- MISSING: {combined}\n-- Run this from the backend directory.\n")

    rule("SECTION 4 of 4  .  Roles")
    out.append("-- The app resolves a user's role by name at registration, so these three\n"
               "-- rows must exist before anyone can sign up. `delivery` is created by\n"
               "-- the delivery_role migration above; these are the original three.\n")
    out.append("INSERT INTO roles (name) VALUES ('customer'), ('farmer'), ('admin')\n"
               "  ON DUPLICATE KEY UPDATE name = VALUES(name);\n")

    out.append("SET FOREIGN_KEY_CHECKS = 1;\n")
    out.append("SELECT CONCAT('F2H schema ready: ', COUNT(*), ' tables') AS result\n"
               "  FROM information_schema.TABLES WHERE TABLE_SCHEMA = DATABASE();")

    return "\n".join(out) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--db", default="f2h_db", help="database name (default: f2h_db)")
    ap.add_argument("--stdout", action="store_true", help="print instead of writing")
    args = ap.parse_args()

    try:
        sql = build(args.db)
    except ImportError as exc:
        sys.exit(
            f"Could not import the app: {exc}\n\n"
            "Run this from the backend directory, with the virtualenv active:\n"
            "    cd backend && source venv/bin/activate\n"
            "    python database/build_full_schema.py"
        )

    if args.stdout:
        print(sql)
        return

    target = HERE / "f2h_complete.sql"
    target.write_text(sql)
    print(f"Wrote {target}  ({len(sql.splitlines())} lines)")
    print("\nOn the target server:\n"
          f"    mysql -u root -p < {target.relative_to(BACKEND)}\n"
          "    python seed_admin.py")


if __name__ == "__main__":
    main()
